apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  selector:
    matchLabels:
      app: portfolio
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: gbt55/portfolio:v1.0.0
        ports:
        - containerPort: 3000
        # env:
        # - name: MI_VARIABLE
        #   value: "pelado"
        # - name: MI_OTRA_VARIABLE
        #   value: "pelade"
        # - name: DD_AGENT_HOST
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "200m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 120
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 120
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  labels:
    name: portfolio
  name: portfolio-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: portfolio